# Generated by Django 4.1.7 on 2023-03-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
